#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push liquidapps/eosio-plugins:$TRAVIS_BRANCH
docker tag liquidapps/eosio-plugins:$TRAVIS_BRANCH liquidapps/eosio-plugins:dummy
docker push liquidapps/eosio-plugins:dummy